name: heyto
description: Live Streaming, Private Video chat and Dating

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  #Default
  cupertino_icons: ^1.0.3
  google_fonts: ^3.0.0

  #Images
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  image_picker: ^0.8.6
  image_compression_flutter: ^1.0.2
  crop: ^0.5.2
  blur: ^3.0.0
  flutter_swipecards: ^0.2.1

  flutter_launcher_icons: ^0.9.2


  #Chat
  sticky_grouped_list: ^2.1.0

  #Backend
  parse_server_sdk_flutter: ^3.1.0

  #Angopapo packages
  linear_progress_bar: ^1.1.0 #This package was developed specially for this app.

  #Utilities
  easy_localization: ^3.0.0
  flutter_native_splash: ^2.1.3+1
  path_provider: ^2.0.10
  rflutter_alert: ^2.0.2
  intl: ^0.17.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.2
  universal_platform: ^1.0.0+1
  stop_watch_timer: ^1.3.1
  flutter_windowmanager: ^0.2.0
  devicelocale: ^0.5.2
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0
  carousel_slider: ^4.0.0
  package_info: ^2.0.2
  permission_handler: any
  rxdart: ^0.27.3
  share_plus: ^4.0.2
  iban: ^1.0.1
  sleek_circular_slider: ^2.0.1
  app_settings: ^4.1.6
  wakelock: ^0.6.2

  #Geo data and phone helper
  country_provider: ^1.0.2
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.4.0
  geocoding: ^2.0.4
  location: ^4.4.0
  #google_places_flutter: ^2.0.5
  flutter_google_places_sdk: ^0.3.2+1

  #Animations
  animations: ^2.0.2
  lottie: ^1.3.0

  #Ads
  google_mobile_ads: ^1.2.0
  advertising_id: ^2.2.0
  app_tracking_transparency: ^2.0.2+1

  #Firebase
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^11.4.0
  firebase_analytics: ^9.1.8
  firebase_performance: ^0.8.0+12
  firebase_crashlytics: ^2.8.0
  firebase_dynamic_links: ^4.2.3

  #Social login
  firebase_auth: 2.0.0
  google_sign_in: ^5.3.1
  google_sign_in_web: ^0.10.1+2
  sign_in_with_apple: ^4.0.0
  flutter_facebook_auth: ^4.3.4

  #gpayments:
  in_app_purchase: ^3.0.4

  #Squeleton
  fade_shimmer: ^2.0.1

  #state management
  provider: ^6.0.2
  http: ^0.13.4
  transparent_image: ^2.0.0
  get: ^4.6.5

  #Calls and live streaming
  agora_rtc_engine: ^5.3.0
  agora_rtm: ^1.1.0
  flutter_ringtone_player: ^3.2.0
  flutter_sound: ^8.4.2
  just_audio: ^0.9.21

  change_app_package_name: ^1.1.0
  flutter_switch: ^0.3.2
  #push notifications
  flutter_local_notifications: ^9.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/card/
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/vector/

flutter_native_splash:
  color: "#ffffff" #White color
  color_dark: "#1d1d35" # Dark color
  fullscreen: true
  image: assets/images/ic_logo.png
  image_dark: assets/images/ic_logo_white.png